### ISSUE TITLE
Enable usage in PyCharm

### ISSUE THREAD

**Issue by dagoltz** [dengzii/AucFrameGenerator#1]
Please allow usage of the plugin in PyCharm - it should work out of the box, as far as I know. I'm happy to be a beta tester :)

**Comment by dengzii** [comment]
@dagoltz
Thank you for your advice and I will try to make it support PyCharm in the next release.

**Comment by dagoltz** [comment]
As described [here](http://www.jetbrains.org/intellij/sdk/docs/basics/getting_started/plugin_compatibility.html), it seems that the issue is the dependency on "**com.intellij.modules.java**".

We currently use this plugin to generate TypeScript Modules (not Java). Some of us use Intllij where this works and some use PyCharm where this plugin not installable.

**Comment by dengzii** [comment]
I changed dependency  to 'com.intellij.modules.platform' and 'com.intellij.modules.lang'.
I tried to install it in WebStorm and GoLand and it worked. it may work on all IntelliJ platforms now, this is [ lastest release](https://github.com/dengzii/GenerateModuleFromTemplate/releases/tag/v1.2)

**Comment by dagoltz** [comment]
Works, thanks!
