### ISSUE TITLE
Ability to import created templates from a specified directory

### ISSUE THREAD

**Issue by mohamed-khaled-hsn** [dengzii/AucFrameGenerator#10]
I find this plugin really useful, thanks for creating it!
one thing I found that's missing, is the ability to have a set of templates in a directory that's under version control and have the plugin automatically import them

**Comment by mohamed-khaled-hsn** [comment]
For example, let's say the plugin requires a directory called "modules_templates" to be in the root directory and it reads from this directory automatically when the action is called

**Comment by dengzii** [comment]
Thanks for your advoice!

This feature was added in version 1.5.4, JetBrains Marketplace will be able to download in two days, or you can install manual by [github release file](https://github.com/dengzii/GenerateModuleFromTemplate/releases/tag/v1.5.4)
