### ISSUE TITLE
Give the possibility to use Velocity's StringUtils in the file name?

### ISSUE THREAD

**Issue by SeifAbdennadherCoolblue** [dengzii/AucFrameGenerator#14]
This feature is already possible in IntelliJ File and Code template; `${StringUtils.removeAndHump(${MODULE_NAME})}Fragment` with `MODULE_NAME = "test_one"` have this result `TestOneFragment`.
It would be nice if can also have the same ability when creating module files

**Comment by SeifAbdennadherCoolblue** [comment]
One suggestion could be to allow the user to not input the file name, then it will use the default from the IntelliJ File template which already supports this feature

**Comment by dengzii** [comment]
Support ApacheVelocity in file name now, enable it from `Module Template Settings` and check `Enable ApacheVelocity`,

Update is uploaded to JetBarinsMarketplace, its availbale to dowload in IDE in 2 business days, or you can install update from [github release v1.6.4](https://github.com/dengzii/GenerateModuleFromTemplate/releases/tag/v1.6.4)

**Comment by dengzii** [comment]
Default file name when edit file tree is also supported now .
