### ISSUE TITLE
安装插件后,创建模板时,包可以创建,但是文件创建时报错

### ISSUE THREAD

**Issue by yatoooon** [dengzii/AucFrameGenerator#15]
插件版本 164
插件安装环境:Android Studio Flamingo | 2022.2.1 Patch 2   Build #AI-222.4459.24.2221.10121639, built on May 12, 2023

我自己打包插件jar后安装创建文件时也会报错:The following files creation failed.

**Comment by yatoooon** [comment]
已解决

**Comment by dengzii** [comment]
是什么问题
