### ISSUE TITLE
Issue in the package name generation using ApacheVelocity API

### ISSUE THREAD

**Issue by SeifAbdennadherCoolblue** [dengzii/AucFrameGenerator#16]
Enabling the ApacheVelocity API is still not working correctly.

I have the plugin template settings set like this
![Screenshot 2023-10-27 at 12 42 15](https://github.com/dengzii/GenerateModuleFromTemplate/assets/119591522/3af841b5-fa38-4da2-b987-67bb4291caaa)

Generating wizard setup like this
![Screenshot 2023-10-27 at 12 43 09](https://github.com/dengzii/GenerateModuleFromTemplate/assets/119591522/3c6ec46e-d2c6-41bf-97b7-37ab0ce8820f)

Preview is correct as seen in this screenshot
![Screenshot 2023-10-27 at 12 43 37](https://github.com/dengzii/GenerateModuleFromTemplate/assets/119591522/31ad4734-b78b-43a6-9299-0ec11f30240a)

But the generated folders/files doesn't apply ApacheVelocity API, and the result looks like this
![Screenshot 2023-10-27 at 12 44 20](https://github.com/dengzii/GenerateModuleFromTemplate/assets/119591522/2680e22d-d92c-409f-a6cc-35d7c24eca63)

**Comment by dengzii** [comment]
Fixed in [v1.6.5](https://github.com/dengzii/GenerateModuleFromTemplate/releases/tag/v1.6.5)
