### ISSUE TITLE
How to export/share setting?

### ISSUE THREAD

**Issue by Dmitriy1892** [dengzii/AucFrameGenerator#17]
How to export/share setting?

**Comment by dengzii** [comment]
![image](https://github.com/dengzii/GenerateModuleFromTemplate/assets/21290064/35e07f50-7609-4b5c-ba9b-3716d222e183)

![image](https://github.com/dengzii/GenerateModuleFromTemplate/assets/21290064/8eab3cf5-9c5d-4f34-80cc-46056612ba48)

**Comment by Dmitriy1892** [comment]
Thank you for answer, but I don't see the menu when clicking to that icon - it opens import settings window. Mac OS Sonoma, Android Studio Hedgehog, plugin version 1.6.4.

![image](https://github.com/dengzii/GenerateModuleFromTemplate/assets/61805972/4252da07-7765-4f60-aecb-7d97993bc4f0)

![image](https://github.com/dengzii/GenerateModuleFromTemplate/assets/61805972/1a297896-ed3d-4252-a2f9-32b95cf80d1f)

**Comment by dengzii** [comment]
This download icon is  for `Export`, for import, click `+` add icon.
