### ISSUE TITLE
[Feature Request] Support path and placeholders in "File Template"

### ISSUE THREAD

**Issue by cpaleop** [dengzii/AucFrameGenerator#18]
Consider not resolving just the `FileName` when setting up File templates. A more complex setup might require different templates to be used in files with the same name but in different folders, see screenshot as example.

The template I'm trying to create is something like the following:
```
feature:
    public:
        //..other files and folders
        build.gradle.kts
    impl:
        //..other files and folders
        build.gradle.kts
```

I obviously need different Android namespaces between them + I need to add the `public` module as an API dependency to the `impl` module. That means that the template for the `build.gradle.kts` of these two modules need to differ.

![image](https://github.com/dengzii/GenerateModuleFromTemplate/assets/16907506/aeb68650-0186-4ade-b97d-097c2e8fe926)

**Comment by dengzii** [comment]
Supported in [Release v1.6.5](https://github.com/dengzii/GenerateModuleFromTemplate/releases/tag/v1.6.5), or JB Marketplace will update in 2 days.

File name can be the last part of full path,  you can simplify the file name to `public/build.gradle.kts`.
