### ISSUE TITLE
[Feature Request] Support path splitting based on the result of Apache Velocity operation

### ISSUE THREAD

**Issue by iwb-cgalvarez** [dengzii/AucFrameGenerator#19]
**Use case**

As a developer, I would like to be able to convert all the symbols from the value of a Placeholder into `.`, so the plugin can split the result of the operation into different folders. Let's give an example:

1. Value of Placeholder `$FEATURE_NAME=test-demo`
2. `${FEATURE_NAME.replaceAll("[^\w]", ".")}` returns `test.demo`
3. The plugin splits `test` and `demo` into different folders making `test` the parent of `demo` (test/demo)

**Current behaviour**

Consider that in the folder tree definition of our module templates we have this Apache velocity code:

<img width="624" alt="Screenshot 2024-02-15 at 10 21 42" src="https://github.com/dengzii/GenerateModuleFromTemplate/assets/85171714/1029ae27-66b1-4f40-8362-54ddad7112b6">

So we have the following configurations:

<img width="615" alt="Screenshot 2024-02-15 at 10 28 00" src="https://github.com/dengzii/GenerateModuleFromTemplate/assets/85171714/e8123cf2-a145-4909-9a6d-77fce0e45ea0">

When input is:

<img width="739" alt="Screenshot 2024-02-15 at 10 28 56" src="https://github.com/dengzii/GenerateModuleFromTemplate/assets/85171714/ab89f307-87cf-44e7-81b3-c6bde89a0cdd">

First the operation seems correct, since the first window is returning `test.demo`:

<img width="738" alt="Screenshot 2024-02-15 at 10 29 52" src="https://github.com/dengzii/GenerateModuleFromTemplate/assets/85171714/1a5b4ffd-9f70-48de-b8c6-17cf52d1e3c6">

But after clicking **Finish** button, the folder split is broken:

<img width="736" alt="Screenshot 2024-02-15 at 10 30 44" src="https://github.com/dengzii/GenerateModuleFromTemplate/assets/85171714/80708f7b-745e-4de6-82a5-099211718faf">

I think the problem here is that instead of splitting the folders based on the result of the apache velocity (which is `test.demo`) is doing the split based on the whole literal definition (so the function with the dots in the middle "${FEATURE_NAME`.`replaceAll(\"[^\\w]\", \"`.`\")}").

Do you think it's something you could consider adding? 

Thank you very much in advance 🙏

**Comment by dengzii** [comment]
🙏 Thank you for bug report, this problem is fixed in `v1.6.6` 🎉 .

You can download it at [GitHub Release](https://github.com/dengzii/GenerateModuleFromTemplate/releases/tag/v1.6.6) or waiting for IDE's plugin update notification.
