### ISSUE TITLE
New files templates do not work in AS Koala

### ISSUE THREAD

**Issue by paxett** [dengzii/AucFrameGenerator#22]
Hello,

when creating New file, there are no files templates available in dropdown list (only some default, probably hardcoded list of templates):
<img width="802" alt="image" src="https://github.com/user-attachments/assets/70f43d31-05f4-498c-a9fa-9f80cbc38c48">

Android Studio Koala | 2024.1.1 Patch 2
Build #AI-241.18034.62.2411.12169540, built on August 1, 2024

Thank you!

**Comment by dengzii** [comment]
Hello, 

Its not hardcode, file templates are search from `Settngs -> Editor -> File and Code Template`, and only user custom template will display in template list

**Comment by paxett** [comment]
Hello,

I have custom file template "My Name Ui", but it's not available in the list:

<img width="1174" alt="image" src="https://github.com/user-attachments/assets/f5a3dde3-c657-4321-9c13-61fff00965bc">

Tested same in Intellij Idea and it works just fine :(

**Comment by dengzii** [comment]
I'm updated my Android Studio to `Koala | 2024.1.1 Patch 2`, Its also working fine， I'm not sure what caused this bug.

<img width="575" alt="image" src="https://github.com/user-attachments/assets/263d28b1-1c4f-48bc-81b2-b4a360594c79">
