### ISSUE TITLE
How to create my own custom classes template

### ISSUE THREAD

**Issue by chaleao** [dengzii/AucFrameGenerator#3]
I noticed that in the folder `fileTemplates` there are some pre defined templates such as `Template MainActivity.java.ft`.

How do I add my own templates?

**Comment by dengzii** [comment]
As you see, just create your file template in this directory, file template end with `.ft` suffix, and then,  you need register template in 
 [`FileTemplateFactory`](https://github.com/dengzii/GenerateModuleFromTemplate/blob/master/src/com/dengzii/plugin/template/template/FileTemplateFactory.kt) , this class extends `FileTemplateGroupDescriptorFactory`, file templates are written with _apache velocity_ .

**Comment by chaleao** [comment]
After adding the files, I assume I would have to generate a .jar from the project

How would I do that in this case?

Most of the example I saw I would need a pom or gradle file.

**Comment by dengzii** [comment]
This project is not a gradle or pom project, but a **IntelliJ Platform Plugin** project, IDEA cannot import this project normally. 

In **IDEA Community** (necessary) `File -> New -> Project from Exsiting Sources -> Create project  from exsiting sources`, then click next until finish import. 

Pressing the `Ctrl + Alt + Shift + S` to open **Project Structure** dialog, choose **Project** tab, change **Project SDK** to `IntelliJ IDEA Community Edition IC-xxxx`, then apply change.

Then, edit `GenerateModuleFromTemplate.iml` in the project root directory, change the `type` attribute  of `module` node to `PLUGIN_MODULE`, minimize the IDEA and restore it, the plugin project will be detected.

Finally, `Run -> Edit Configuretions -> Alt + Insert -> Plugin -> Apply`, the project configuration completed.

Generate .jar : `Run -> Prepare Plugin Module xxx For Deployment`

**Comment by chaleao** [comment]
@dengzii I was applying to import and generate the .jar file by following the steps above, but for some reason after I install the plugin I don't see anything in the `Module Template Settings` and also the popup to create the module doesn't show up.

do you know what could be happening?
