### ISSUE TITLE
How to use IntelliJ-managed templates

### ISSUE THREAD

**Issue by RaveKev** [dengzii/AucFrameGenerator#4]
I try to use a template that i created in IntelliJ.
The generate file keeps empty. Do i miss anything?

**Comment by dengzii** [comment]
@RaveKev 
 Confirm the TemplateFile must be same with the template you created in IDE, and selecte the target template in the `New File` dialog when you edit file tree.

In the `New File` dialog, you can see the exist template.

**Comment by RaveKev** [comment]
Hm, i try :-) 

![nOXV00TDPV](https://user-images.githubusercontent.com/11254211/100463833-c286ae00-30cc-11eb-93e1-c4884e91fdc0.gif)

https://youtu.be/mX8yNMfmtEE

**Comment by dengzii** [comment]
I repeated the bug, I'm trying to fix it, thanks for you rating 😀

**Comment by RaveKev** [comment]
> I repeated the bug, I'm trying to fix it, thanks for you rating 😀

I had to vote. I wanted to start making such a plugin by myself, but i had to learn the Plugindevelopment first - so i was happy to find yours :)

**Comment by dengzii** [comment]
I'm glad I can help you, I'm also learning to develop plugin, you can discuss to me if you have any questions about this plugin or when you development plugin.
You can Email to me(dengzii@foxmail.com), or create issue, I will get back to you right away.

**Comment by dengzii** [comment]
Fixed in version [1.5.0](https://github.com/dengzii/GenerateModuleFromTemplate/releases/tag/V1.5.0)
