### ISSUE TITLE
How to generate folder and file with this plugin?

### ISSUE THREAD

**Issue by pytkr** [dengzii/AucFrameGenerator#5]
Hello, I tried with this plugin and have no idea how to make use of this json file it exports, namely, how to generate the structure and file.

Another problem is how to edit file in the new file panel, or include existant file as template file, and this plugin can recognise the placeholder automatically.

Anyway, Thank you for sharing this plugin.

**Comment by dengzii** [comment]
Hello, the json file is used to share your templates with others.

You can edit file/directory tree, but not file content, the file template is use IDE build-in feature, you can find it in `Settings > Editor > File and Code Templates > Files`, when you `New File` on file/directory tree, you can select template and use it on  `Template` , this field listed IDE's file template.

**Comment by pytkr** [comment]
> Hello, the json file is used to share your templates with others.
> 
> You can edit file/directory tree, but not file content, the file template is use IDE build-in feature, you can find it in `Settings > Editor > File and Code Templates > Files`, when you `New File` on file/directory tree, you can select template and use it on `Template` , this field listed IDE's file template.

Thanks for your reply, and hope tutorial be more enhanced to learn.

**Comment by dengzii** [comment]
The video tutorial [Youtube](https://www.youtube.com/watch?v=TyeXnbCcBP4)
