### ISSUE TITLE
占位符

### ISSUE THREAD

**Issue by huangjia0202** [dengzii/AucFrameGenerator#6]
怎么使用占位符，让创建文件的名字能随着包名有变化

**Comment by dengzii** [comment]
你可以先定义一个叫 PackageName 的占位符, 或者创建目录的时候直接把包名命名成 ${PackageName}, PackageName 中如果有点, 会自动展开成多个目录, 然后文件的名字命名成 ${PakcageName}.Java, 文件名就和包名一样了
