### ISSUE TITLE
请不要把文件名强行首字母大写，或者提供开关进行控制

### ISSUE THREAD

**Issue by zieglar** [dengzii/AucFrameGenerator#8]
非常感谢您提供这么好的插件给大家使用，但是因为我不是用在Java项目上，不需要文件名首字母大写，使用这个创建以后需要把所有的文件名再改一遍，能否提供开关进行控制，或者允许在最终界面上创建文件之前进行修改？

**Comment by dengzii** [comment]
感谢你的建议, 下次更新我就采取你的建议.

**Comment by zieglar** [comment]
在占位符的使用上，是否可以使用已有占位符拼成一个新的占位符，譬如
```
app = uis
modelName = department
entityName = UisDepartment 
```
也就是`entityName = "$app.substring(0,1).toUpperCase()$app.substring(1)${modelName}"` 这样的写法
在模版里，下面这一段是有效的
```
#set( $part = "" )
#foreach($part in $NAME.split("-"))
  #set( $moduleName = "${moduleName}$part.substring(0,1).toUpperCase()$part.substring(1).toLowerCase()" )
#end
```

**Comment by dengzii** [comment]
@zieglar  理论上可以实现类似于这种 `${${AAA}_${BBB}}` , 但是比较复杂, 得看看

**Comment by zieglar** [comment]
期待更新！

**Comment by dengzii** [comment]
已经更新了, 支持占位符嵌套和自定义文件名大小写, 插件市场还在审核, 手动安装:  [Release V1.5.2](https://github.com/dengzii/GenerateModuleFromTemplate/releases/tag/v1.5.2)
