### ISSUE TITLE
文件名重复但在不同目录时，会覆盖前一个同名文件的设置

### ISSUE THREAD

**Issue by zieglar** [dengzii/AucFrameGenerator#9]
<img width="313" alt="CleanShot 2022-03-02 at 17 00 08@2x" src="https://user-images.githubusercontent.com/514693/156329177-c7c2446f-639f-47db-bdd2-46901de2126a.png">

如图所示，dto内 index.ts使用的模版会覆盖 根目录下index.ts的模版设置，使得最后生成的文件根目录下的index.ts和dto/index.ts内容一致。

另外有空的时候麻烦更新下占位符嵌套写法的文档。

感谢🙏

**Comment by zieglar** [comment]
目前使用下来发现可以复用模版的 live template ，之前以为不行

**Comment by dengzii** [comment]
占位符嵌套就直接嵌套呀, 一层层往外解析, 大噶是这样, 设置占位符 A=a, B=b, a_b=c,  `${${A}_${B}}` 合并成 `${a_b}` 然后再替换成 `c`
`
内容一致是因为使用了相同的文件模板吧, 目前相同名字的文件不支持使用不同模板

**Comment by zieglar** [comment]
<img width="493" alt="CleanShot 2022-03-03 at 15 07 30@2x" src="https://user-images.githubusercontent.com/514693/156514319-13d1034f-7351-495d-b25a-2cf158c42ebb.png">

试了下未能正常解析嵌套

**Comment by dengzii** [comment]
@zieglar 你是说文件模板的吗, 这个不行

不是, 这个占位符的值不能使用占位符, 不能这样用....占位符名称可以嵌套, 比如顶一个叫 `${name}s` 的占位符

**Comment by zieglar** [comment]
我在占位符上用的是 ${name}s 指定给占位符 path，文件模版里使用的是 ${path}，但是被解析为 ${name}s ，所以这样是不行的？

**Comment by dengzii** [comment]
对, 这样是不行的, 占位符的值不会解析

**Comment by zieglar** [comment]
了解了 XD
